all: _build/2.7.0.1/agda/source/index-8-0.agdai 

_build/2.7.0.1/agda/source/index-0-0.agdai: 
	agda ./source/index-0-0.lagda

_build/2.7.0.1/agda/source/index-1-0.agdai: _build/2.7.0.1/agda/source/index-0-0.agdai 
	agda ./source/index-1-0.lagda

_build/2.7.0.1/agda/source/index-1-1.agdai: _build/2.7.0.1/agda/source/index-0-0.agdai 
	agda ./source/index-1-1.lagda

_build/2.7.0.1/agda/source/index-2-0.agdai: _build/2.7.0.1/agda/source/index-1-0.agdai _build/2.7.0.1/agda/source/index-1-1.agdai 
	agda ./source/index-2-0.lagda

_build/2.7.0.1/agda/source/index-3-0.agdai: _build/2.7.0.1/agda/source/index-2-0.agdai 
	agda ./source/index-3-0.lagda

_build/2.7.0.1/agda/source/index-3-1.agdai: _build/2.7.0.1/agda/source/index-2-0.agdai 
	agda ./source/index-3-1.lagda

_build/2.7.0.1/agda/source/index-4-0.agdai: _build/2.7.0.1/agda/source/index-3-0.agdai _build/2.7.0.1/agda/source/index-3-1.agdai 
	agda ./source/index-4-0.lagda

_build/2.7.0.1/agda/source/index-5-0.agdai: _build/2.7.0.1/agda/source/index-4-0.agdai 
	agda ./source/index-5-0.lagda

_build/2.7.0.1/agda/source/index-5-1.agdai: _build/2.7.0.1/agda/source/index-4-0.agdai 
	agda ./source/index-5-1.lagda

_build/2.7.0.1/agda/source/index-5-2.agdai: _build/2.7.0.1/agda/source/index-4-0.agdai 
	agda ./source/index-5-2.lagda

_build/2.7.0.1/agda/source/index-6-0.agdai: _build/2.7.0.1/agda/source/index-5-0.agdai _build/2.7.0.1/agda/source/index-5-1.agdai _build/2.7.0.1/agda/source/index-5-2.agdai 
	agda ./source/index-6-0.lagda

_build/2.7.0.1/agda/source/index-7-0.agdai: _build/2.7.0.1/agda/source/index-6-0.agdai 
	agda ./source/index-7-0.lagda

_build/2.7.0.1/agda/source/index-7-1.agdai: _build/2.7.0.1/agda/source/index-6-0.agdai 
	agda ./source/index-7-1.lagda

_build/2.7.0.1/agda/source/index-7-2.agdai: _build/2.7.0.1/agda/source/index-6-0.agdai 
	agda ./source/index-7-2.lagda

_build/2.7.0.1/agda/source/index-7-3.agdai: _build/2.7.0.1/agda/source/index-6-0.agdai 
	agda ./source/index-7-3.lagda

_build/2.7.0.1/agda/source/index-8-0.agdai: _build/2.7.0.1/agda/source/index-7-0.agdai _build/2.7.0.1/agda/source/index-7-1.agdai _build/2.7.0.1/agda/source/index-7-2.agdai _build/2.7.0.1/agda/source/index-7-3.agdai 
	agda ./source/index-8-0.lagda

